[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_event = 'InsertEnter'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_source = '''
    let g:vimtex_compiler_latexmk = {'callback' : 0}
    let g:vimtex_view_enabled = 0
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
"    let g:quickrun_config = {'*': {'hook/time/enable': '1'}}
    let g:quickrun_config = get(g:, 'quickrun_config', {})
    let g:quickrun_config._ = {
        \ 'runner'    : 'vimproc',
        \ 'runner/vimproc/updatetime' : 60,
        \ 'outputter' : 'error',
        \ 'outputter/error/success' : 'buffer',
        \ 'outputter/error/error'   : 'quickfix',
        \ 'outputter/buffer/split'  : ':rightbelow 8sp',
        \ 'outputter/buffer/close_on_empty' : 1,
        \ }
    au FileType qf nnoremap <silent><buffer>q :quit<CR>
    let g:quickrun_no_default_key_mappings = 1
    nnoremap \r :write<CR>:QuickRun -mode n<CR>
    xnoremap \r :<C-U>write<CR>gv:QuickRun -mode v<CR>
    let g:quickrun_no_default_key_mappings = 1
    nnoremap \r :cclose<CR>:write<CR>:QuickRun -mode n<CR>
    xnoremap \r :<C-U>cclose<CR>:write<CR>gv:QuickRun -mode v<CR>
    nnoremap <expr><sile\t> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
'''

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'
on_path = '.*'
hook_source = 'nmap <silent> <C-u><C-u> :<C-u>Denite file_mru<CR>'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = 'denite.nvim'
on_event = 'TextYankPost'
hook_source = 'nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>'

[[plugins]]
repo = 'suan/vim-instant-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_source = '''
    " rename用のマッピングを無効にしたため、代わりにコマンドを定義
    " command! -nargs=0 JediRename :call jedi#rename()

    let g:jedi#rename_command = "<leader><C-r>"
    let g:jedi#documentation_command = "<C-k>"
'''

[[plugins]]
repo = 'pmsorhaindo/syntastic-local-eslint.vim'
on_ft = 'javascript'
