[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_source = '''
    let g:vimtex_compiler_latexmk = {'callback' : 0}
    let g:vimtex_view_enabled = 0
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ['tex']
hook_source = '''
    let g:quickrun_config = {'*': {'hook/time/enable': '1'}}
'''

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/vimshell'
rev = '3787e5'
cmd = 'VimShell'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'
on_path = '.*'
hook_source = 'nmap <silent> <C-u><C-u> :<C-u>Denite file_mru<CR>'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = 'denite.nvim'
on_event = 'TextYankPost'
hook_source = 'nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>'
