[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let NERDTreeShowHidden = 1
    nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
depends = 'nerdtree'
hook_add = '''
    if argc() == 0
        let g:nerdtree_tabs_open_on_console_startup = 1
    end
'''

[[plugins]]
repo = 'tomasr/molokai'
