set-option -gw mode-keys vi
set -g prefix C-j
unbind C-b
bind c-j send-prefix

set-option -g default-terminal screen-256color
set -g terminal-overrides "xterm:colors=256"
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# prefix + m でマウスモードのON/OFFを切り替え
bind m run-shell '
  if [ "$(tmux show -g -v mouse)" = "on" ]; then
    tmux set -g mouse off
  else
    tmux set -g mouse on
  fi
'

set-option -s set-clipboard on
bind-key -T copy-mode-vi v { send-keys -X begin-selection }
bind-key -T copy-mode-vi C-v { send-keys -X rectangle-toggle }
bind-key -T copy-mode-vi V { send-keys -X select-line }
bind-key -T copy-mode-vi y { send-keys -X copy-pipe-and-cancel "pbcopy" }
bind-key -T copy-mode-vi C-[ { send-keys -X clear-selection }
unbind-key -T copy-mode-vi MouseDragEnd1Pane

set -g status-right "#{?#{==:#{pane_mode},copy-mode},COPY | ,}Mouse: #{?mouse,on,off} | %Y-%m-%d %H:%M "

if-shell "[ -f ~/.config/tmux/tmux.local.conf ]" \
  "source-file ~/.config/tmux/tmux.local.conf"
