set-option -gw mode-keys vi
set -g prefix C-j
unbind C-b
bind c-j send-prefix

set-option -g default-terminal screen-256color
set -g terminal-overrides "xterm:colors=256"
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# prefix + m でマウスモードのON/OFFを切り替え
bind m run-shell '
  if [ "$(tmux show -g -v mouse)" = "on" ]; then
    tmux set -g mouse off
  else
    tmux set -g mouse on
  fi
'

set-option -s set-clipboard on
bind-key -T copy-mode-vi v { send-keys -X begin-selection }
bind-key -T copy-mode-vi C-v { send-keys -X rectangle-toggle }
bind-key -T copy-mode-vi V { send-keys -X select-line }
bind-key -T copy-mode-vi y { send-keys -X copy-pipe-and-cancel "pbcopy" }
bind-key -T copy-mode-vi C-[ { send-keys -X clear-selection }
unbind-key -T copy-mode-vi MouseDragEnd1Pane

# ステータスライン
set-option -g @c-base "#000000"
set-option -g @c-base-content "#FFFFFF"
set-option -g @c-primary "#BEFF00"
set-option -g @c-primary-content "#507000"
set-option -g @c-neutral "#485159"
set-option -g @c-neutral-content "#D3DCE8"
set-option -g @c-info-content "#FE3B00"
set-option -g @c-copy "#EDBD11"
set-option -g @c-copy-content "#000000"
set-option -g @c-mouse "#D3DCE8"
set-option -g @c-mouse-content "#000000"

set-option -g status-style "bg=#{@c-base},fg=#{@c-base-content}"
set-option -g status-left " #S "
set-option -gw window-status-bell-style "bold"
set-option -gw window-status-format '#( \
  label=" #W "; \
  bg="#{@c-neutral}"; \
  fg="#{@c-neutral-content}"; \
  if [ "#{window_bell_flag}" = "1" ]; then \
    label=" ! #W "; \
    fg="#{@c-info-content}"; \
  fi; \
  echo "#[bg=$bg,fg=$fg]$label"; \
)'
set-option -gw window-status-current-format '#( \
  label=" #W "; \
  bg="#{@c-primary}"; \
  fg="#{@c-primary-content}"; \
  echo "#[bg=$bg,fg=$fg,bold]$label"; \
)'
set-option -g status-right '#(\
  copy_bg="#{@c-copy}"; \
  copy_fg="#{@c-copy-content}"; \
  copy_label="#{?#{==:#{pane_mode},copy-mode},#[bg=$copy_bg]#[fg=$copy_fg] Copy #[default],} "; \
  mouse_bg="#{@c-mouse}"; \
  mouse_fg="#{@c-mouse-content}"; \
  mouse_label="#{?mouse,#[bg=$mouse_bg]#[fg=$mouse_fg] Mouse #[default],} "; \
  time="%Y-%m-%d %H:%M"; \
  echo "$copy_label$mouse_label$time "; \ 
)'

# ローカル設定
if-shell "[ -f ~/.config/tmux/tmux.local.conf ]" \
  "source-file ~/.config/tmux/tmux.local.conf"
