set -g prefix C-j
unbind C-b
bind c-j send-prefix
# tmux内でも同じ色が出るように設定
set-option -g default-terminal screen-256color
set -g terminal-overrides "xterm:colors=256"
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# m キーでマウス操作のオンオフを切り替える
bind m run-shell '
  if [ "$(tmux show -g -v mouse)" = "on" ]; then
    tmux set -g mouse off
  else
    tmux set -g mouse on
  fi
'
# ステータスバーにマウス状態の表示を追加
set -g status-right 'Mouse: #{?mouse,on,off} | %Y-%m-%d %H:%M '

if-shell "[ -f ~/.config/tmux/tmux.local.conf ]" \
  "source-file ~/.config/tmux/tmux.local.conf"
