git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
gui:
  language: "ja"
  showIcons: true

customCommands:
  - command: meteor
    context: files
    output: terminal
    key: C
